version: '2'
services:
  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"   
    volumes:
      - ./mongodb:/data/db  
  mongo-seed:
    image: sessiontalk/sessionflow_seed_data
    links:
      - mongo
  web:
    image: sessiontalk/sessionflow
    ports:
     - "1337:1337"
     - "6000:6000"
    depends_on:
     - mongo
    restart: always 
    volumes:
      - ./files/certs:/sessionflow/files/certs 
    links:
      - mongo  
   
